# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_auto_20151207_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutiqueline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u7cbe\u54c1\u8def\u7ebf\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='boutiqueline',
            name='pic_address',
            field=models.CharField(max_length=255, verbose_name='\u56fe\u7247\u5730\u5740'),
        ),
    ]
