# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_auto_20151208_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutiquelinedetails',
            name='approach',
            field=models.CharField(max_length=255, null=True, verbose_name='\u9014\u5f84\u5730\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='boutiquelinedetails',
            name='day_numbers',
            field=models.IntegerField(verbose_name='\u7b2c\u51e0\u5929'),
        ),
        migrations.AlterField(
            model_name='boutiquelinedetails',
            name='detail_pic_address',
            field=models.TextField(null=True, verbose_name='\u6bcf\u5f20\u56fe\u7684\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='boutiquelinedetails',
            name='detail_pic_number',
            field=models.IntegerField(null=True, verbose_name='\u5c0f\u56fe\u7684\u6570\u76ee'),
        ),
        migrations.AlterField(
            model_name='boutiquelinedetails',
            name='may_pic_address',
            field=models.CharField(max_length=255, null=True, verbose_name='\u5730\u56fe\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='boutiquelinedetails',
            name='node_details',
            field=models.TextField(null=True, verbose_name='\u8def\u9014\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='approach',
            field=models.CharField(max_length=255, null=True, verbose_name='\u9884\u7559\u9014\u5f84\u5730'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='days',
            field=models.PositiveIntegerField(null=True, verbose_name='\u9884\u8ba1\u6e38\u73a9\u5929\u6570'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='\u7528\u6237\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='\u9884\u8ba1\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='privateorder',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u5b8c\u6210\u72b6\u6001'),
        ),
    ]
