# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('pic_address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BoutiqueLineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_numbers', models.IntegerField()),
                ('node_details', models.TextField()),
                ('may_pic_address', models.CharField(max_length=255)),
                ('approach', models.CharField(max_length=255)),
                ('detail_pic_number', models.IntegerField()),
                ('detail_pic_address', models.TextField()),
                ('boutiqueline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bboutique_line', to='tourism.BoutiqueLine')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('destination', models.CharField(max_length=255)),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('approach', models.CharField(max_length=255)),
            ],
        ),
    ]
