# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_auto_20151208_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateorder',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210'), (-1, '\u53d6\u6d88\u8ba2\u5355')], default=0, verbose_name='\u5b8c\u6210\u72b6\u6001'),
        ),
    ]
