# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_auto_20151209_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutiqueline',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
