# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2015-12-20 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_auto_20151220_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateorder',
            name='hotel',
            field=models.CharField(max_length=60, null=True, verbose_name='\u4f4f\u5bbf'),
        ),
        migrations.AddField(
            model_name='privateorder',
            name='travel_requirement',
            field=models.CharField(max_length=255, null=True, verbose_name='\u51fa\u884c\u8981\u6c42'),
        ),
    ]
